# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
# Collections
collections: 
  works:
    output: true
    permalink: /works/:path/

# Site settings
title: Corinne Kunze - Web Developer With An Eye for Design
email: corinnekunze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Corinne Kunze is a web developer who strives to create beautiful user experiences as well as logical and maintainable codebases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.corinnekunze.com" # the base hostname & protocol for your site
twitter_username: corinnekunze
github_username:  corinnekunze
destination: docs

# Build settings
markdown: kramdown
markdown_ext: "markdown, mkdown, mkdn, mkd, md"


